version: 2.1
jobs:
  test:
    docker:
      - image: corcleci/node:6-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run:
          name: install node modules
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: depandency-cache-{{ checksum "package.json" }}
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Unit Tests
          command: npm run test
      - run:
          name: Build
          command: npm run build --env=production
