version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:lts-buster-browsers-legacy
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run:
          name: install node modules
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: depandency-cache-{{ checksum "package.json" }}
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Unit Tests
          command: npm run test
  deploy:
    docker:
      - image: circleci/node:lts-buster-browsers-legacy
    steps:
      - checkout
      - run:
          name: install node modules
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: depandency-cache-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npm run build --env=production
      - run:
          name: tar
          command: tar -C ./dist/portfolio -zcvf portfolio.tar.gz ./
      - aws-s3/copy:
          # arguments: '--recursive'
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: ./portfolio.tar.gz
          to: 's3://ytakahashi-portfolio'
workflows:
  test_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
            tags:
              only: /v\d+\.\d+\.\d+/
orbs:
  aws-s3: circleci/aws-s3@2.0.0
