version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:lts-buster-browsers-legacy
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run:
          name: install node modules
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: depandency-cache-{{ checksum "package.json" }}
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Unit Tests
          command: npm run test
  build:
    docker:
      - image: circleci/node:lts-buster-browsers-legacy
    steps:
      - run:
          name: Build
          command: npm run build --env=production
      - aws-s3/copy:
          arguments: '--recursive'
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: ./dist/portfolio
          to: 's3://ytakahashi-portfolio'
workflows:
  test_and_build:
    jobs:
      - test
      - build
orbs:
  aws-s3: circleci/aws-s3@2.0.0
